import { redirect } from 'next/navigation';

import { getCurrentUser } from '@/lib/auth/server';

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default async function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  if (!user) {
    redirect('/sign-in');
  }

  return <div className="p-8">{children}</div>;
}
