export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
